Ruby Project: Solo
rkyankya/Microverse-Enumerable pull request #1
Opened 2019-10-11 10:19 UTC by rkyankya

Enumerables

2019-10-12 03:05 UTC, Ispirett commented
**Please use Gitflow for this project and resubmit for review.**

2019-10-14 17:02 UTC, mcrd25 requested changes
# Changes Required

Hi @rkyankya 👋,

Please close this pull request and resubmit using [Git Flow](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/).
***How Git Flow Works***
  - You'd have the `master` branch purely for production purposes 
  - the `development` branch would act as the main working branch where you create merge requests from `feature` branches to `development` for reviews on these requests
  - If you are requesting a review for a project without multiple milestones simply have one main `feature` branch (appropriately named) that you can then branch off from and merge to accordingly as you complete your project. 
  - After you have completed your project and it's ready for your first review you can then request a code review form your main `feature` branch to `development` branch
  - Once the pull request is approved you can then merge this pull request
  - You would then merge the `development` branch to `master` branch 

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_each
`my_each` should return enumerator when block not given.

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_each_with_index
`my_each_with_index` should return enumerator when block not given.

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_select
`my_select` should return enumerator when block not given.

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_each_with_index
Additional Requirements for this method:
it should:
- return an Enumerator if no block is given

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_each
Additional Requirements for this method:
it should:
- return an Enumerator if no block is given

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_select
Additional Requirements for this method:
it should:
- return an Enumerator if no block is given

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_all?(arg1 = nil)
Additional Requirements for this method:
it should:
- return true when no block or argument is given and none of the collection members are false or nil
- return true when a class is passed as an argument and all of the collection is a member of such class
- return true when a Regex is passed as an argument and all of the collection matches the Regex
- return true when a pattern other than Regex or a Class is given and if all of the collection matches the pattern

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_all?(arg1 = nil)
[OPTIONAL]
Also, this is a really long method!
Surely there is way to shorten it? 
You can use your my_each and make simpler comparisons.

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_any?
Additional Requirements for this method:
it should:
- return true when no block or argument is given and at least one of the collection members are false or nil
- return true when a class is passed as an argument and at least one of the collection is a member of such class
- return true when a Regex is passed as an argument and at least one of the collection matches the Regex
- return true when a pattern other than Regex or a Class is given and if at least one of the collection matches the pattern

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_none?
Additional Requirements for this method:
it should:
- return true when no block or argument is given and none of the collection members are true
- return true when a class is passed as an argument and not one of the collection is a member of such class
- return true when a Regex is passed as an argument and not one of the collection matches the Regex
- return true when a pattern other than Regex or a Class is given and if not one of the collection matches the pattern

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_count(obj = nil)
[OPTIONAL]
using my_each may decrease the length of this method.

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_map
Additional Requirements for this method:
it should:
- return an Enumerator if no block is given

2019-10-14 17:02 UTC, mcrd25 commented on enum_methods.rb
> +  def my_inject(arg1 = 1, sbl = nil)
Your inject does not pass any of our tests 😢 

It should:
- return combination of all elements of enum by applying a binary operation, specified by a block
- return combination of each element of the collection by applying the symbol as a named method when a symbol is specified

2019-10-15 15:55 UTC, closed without merging